name: Build And Deploy Docker Image

on:
  workflow_dispatch:
    branches: ["main"]
  push:
    branches: ["main"]

env:
  REGISTRY: gcr.io
  IMAGE_NAME: calm-axis-398119/landing-frontend-app
  
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Auth in google
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '>= 363.0.0'
      - name: Configure docker to use the gcloud command-line tool as a credential helper
        run: gcloud auth configure-docker
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value={{branch}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Not Checkout
      uses: actions/checkout@v3
    - name: Auth in google
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: '>= 363.0.0'
    - name: Deploy new revision
      run: gcloud run deploy landing-frontend-app --region europe-north1 --image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}